version: "3.9" 

services:
  app:
    build: 
      context: .
      dockerfile: drf_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./drf_api:/app
    env_file:
      - drf_api/.env
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    restart: always
    env_file:
      - drf_api/.env
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"  


  redis_exporter: 
    image: oliver006/redis_exporter
    command:
      - '--redis.addr=redis:6379'
    ports:
        - "9121:9121"
    depends_on:
      - redis


  prometheus:
    image: prom/prometheus   
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"          

  grafana:
    image: grafana/grafana  
    ports:
      - "3000:3000"         
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana 

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus


volumes:
  postgres-data:
  dev-db-data:
  grafana-storage: 