version: "3.9" 

services:
  app:
    build: 
      context: .
      dockerfile: drf_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./drf_api:/app
    env_file:
      - drf_api/.env
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    restart: always
    env_file:
      - drf_api/.env
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"   

volumes:
  postgres-data: