# Generated by Django 5.1.13 on 2025-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
