# Generated by Django 5.1.12 on 2025-09-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.UUIDField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
