# Generated by Django 5.1.12 on 2025-09-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        ('user', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_type', models.CharField(choices=[('교재용', '교재용'), ('학습용', '학습용'), ('자습용', '자습용')], max_length=10)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folder.folder')),
                ('invited_students', models.ManyToManyField(blank=True, related_name='invited_files', to='user.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.userprofile')),
            ],
        ),
    ]
